import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');
export const CARD_WIDTH = (width - 40) / 2;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F8FB' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginBottom: 10,
    marginTop: 20,
  },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#222' },
  icon: { width: 24, height: 24, resizeMode: 'contain' },
  cartBtn: { position: 'relative' },
  badge: {
    position: 'absolute',
    top: -5,
    right: -8,
    backgroundColor: '#FF3B6B',
    borderRadius: 10,
    paddingHorizontal: 5,
  },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  banner: {
    marginHorizontal: 20,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    elevation: 5,
    marginBlock: 20,
  },
  bannerText: { flex: 1 },
  bannerTitle: { color: '#FFD700', fontSize: 13, fontWeight: '700' },
  bannerSubtitle: { color: '#fff', fontSize: 16, fontWeight: '600', marginTop: 4 },
  bannerImage: { width: 100, height: 100, resizeMode: 'contain' },
  listContainer: { paddingHorizontal: 10, paddingBottom: 120 },
  row: { justifyContent: 'space-between' },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    width: CARD_WIDTH,
    padding: 25,
    marginBottom: 16,
    elevation: 3,
  },
  discountTag: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#FF4081',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    zIndex: 1,
  },
  discountText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  productImage: { width: '100%', height: CARD_WIDTH * 0.7, resizeMode: 'contain', borderRadius: 10 },
  productName: { fontSize: 13, fontWeight: '600', marginTop: 8 },
  soldText: { fontSize: 11, color: '#666', marginTop: 3 },
  progressBar: { height: 6, backgroundColor: '#E5E8F0', borderRadius: 6, marginTop: 5, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#6C8CFF' },
  priceText: { fontSize: 14, fontWeight: '700', color: '#000', marginTop: 6 },
  floatingButton: {
    position: 'absolute',
    bottom: 28,
    alignSelf: 'center',
    backgroundColor: '#4A7DFF',
    borderRadius: 40,
    padding: 16,
    elevation: 8,
  },
  searchIcon: { width: 24, height: 24, tintColor: '#fff' },
});
